# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChamadaServer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaAsyncSocket'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

  # Pods for ChamadaServer

  target 'ChamadaServerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChamadaServerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
